spring:
  datasource:
    url: jdbc:mysql://120.76.136.205:3306/db3?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 9gsg642f-fdg6hr82f1!6f
#    password: 140010
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 120.76.136.205
      database: secondhand
      port: 27017
      username: root
      password: 9gsg642f-fdg6hr82f1!6f
      option:
        #一个线程等待链接可用的最大等待毫秒数，0表示不等待，负数表示等待时间不确定，推荐配置120000
        max-wait-time: 120000
        #链接超时的毫秒数,0表示不超时,此参数只用在新建一个新链接时，推荐配置10,000.
        connect-timeout: 10000
        #此参数表示socket I/O读写超时时间,推荐为不超时，即 0    Socket.setSoTimeout(int):60000
        socket-timeout: 60000


        min-connection-per-host: 0
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 30000
        max-connection-idle-time: 60000
        max-connection-life-time: 0
        socket-keep-alive: true
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15

server:
  port: 8888
  tomcat:
    uri-encoding: utf-8
    basedir: /java/local/springboot-vue-after/data   #指定目录

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml




